// Report Generation Service
import { jsPDF } from 'jspdf';
import { searchReferences, Reference } from './pubmed-service';

interface AnalysisData {
  id: string;
  analysis: string;
  findings?: Array<{ finding: string }> | string[];
  keywords?: Array<{ keyword: string }> | string[];
  filename?: string;
  createdAt?: Date | string;
}

export async function generateReport(
  data: AnalysisData,
  includeReferences: boolean = true
): Promise<Blob> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = margin;

  // Helper function to add text with word wrap
  const addText = (text: string, fontSize: number = 11, isBold: boolean = false) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    const lines = doc.splitTextToSize(text, pageWidth - 2 * margin);
    
    for (const line of lines) {
      if (yPosition > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
      doc.text(line, margin, yPosition);
      yPosition += fontSize * 0.5;
    }
    yPosition += 5;
  };

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Medical Analysis Report', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Metadata
  addText(`Date: ${new Date().toLocaleString()}`, 11, true);
  addText(`Report ID: ${data.id || 'N/A'}`, 11, true);
  
  if (data.filename) {
    addText(`Source File: ${data.filename}`, 11, true);
  }
  
  yPosition += 10;

  // Analysis
  if (data.analysis) {
    addText('Detailed Analysis', 14, true);
    addText(data.analysis, 11, false);
    yPosition += 5;
  }

  // Findings
  if (data.findings && data.findings.length > 0) {
    addText('Key Findings', 14, true);
    
    const findingsArray = Array.isArray(data.findings) 
      ? data.findings.map(f => typeof f === 'string' ? f : f.finding)
      : [];
    
    findingsArray.forEach((finding, index) => {
      addText(`${index + 1}. ${finding}`, 11, false);
    });
    yPosition += 5;
  }

  // Keywords
  if (data.keywords && data.keywords.length > 0) {
    addText('Keywords / Tags', 14, true);
    
    const keywordsArray = Array.isArray(data.keywords)
      ? data.keywords.map(k => typeof k === 'string' ? k : k.keyword)
      : [];
    
    addText(keywordsArray.join(', '), 11, false);
    yPosition += 5;
  }

  // References
  if (includeReferences && data.keywords) {
    const keywordsArray = Array.isArray(data.keywords)
      ? data.keywords.map(k => typeof k === 'string' ? k : k.keyword)
      : [];
    
    const references = await searchReferences(keywordsArray, 3);
    
    if (references.length > 0) {
      addText('Relevant References', 14, true);
      
      references.forEach((ref, index) => {
        addText(`${index + 1}. ${ref.title} (${ref.source}, ${ref.year})`, 11, false);
      });
    }
  }

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text(
    'This report is generated by AI and should be reviewed by a medical professional.',
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  return doc.output('blob');
}

export async function generateStatisticsReport(analyses: AnalysisData[]): Promise<Blob> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = margin;

  const addText = (text: string, fontSize: number = 11, isBold: boolean = false) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    const lines = doc.splitTextToSize(text, pageWidth - 2 * margin);
    
    for (const line of lines) {
      doc.text(line, margin, yPosition);
      yPosition += fontSize * 0.5;
    }
    yPosition += 5;
  };

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Medical Imaging Statistics Report', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Overall Statistics
  addText('Overall Statistics', 14, true);
  addText(`Total analyses: ${analyses.length}`, 11, false);
  yPosition += 10;

  // Extract keyword counts
  const keywordCounts: Record<string, number> = {};
  
  analyses.forEach(analysis => {
    if (analysis.keywords) {
      const keywordsArray = Array.isArray(analysis.keywords)
        ? analysis.keywords.map(k => typeof k === 'string' ? k : k.keyword)
        : [];
      
      keywordsArray.forEach(keyword => {
        keywordCounts[keyword] = (keywordCounts[keyword] || 0) + 1;
      });
    }
  });

  // Sort keywords by frequency
  const sortedKeywords = Object.entries(keywordCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10);

  if (sortedKeywords.length > 0) {
    addText('Common Findings', 14, true);
    sortedKeywords.forEach(([keyword, count]) => {
      addText(`${keyword}: ${count} occurrences`, 11, false);
    });
  }

  return doc.output('blob');
}
